framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(MAILER_FROM_ADDRESS)%'
        headers:
            From: '%env(MAILER_FROM_NAME)% <%env(MAILER_FROM_ADDRESS)%>'
            # Header personnalis√© pour le tracking
            X-Application: 'CFA-Gestion'
